### ISSUE TITLE
Alternative way to use redux

### ISSUE THREAD

**Issue by sz-piotr** [martynaskadisa/react-use-redux#3]
Hey :) Are you maintaining this library? I am here to propose an alternative approach that does not require using context.

I could create my own library but the name of your package is the most fitting for this so I present you with an option to integrate my idea into your library.

The entire library code:
```typescript
import { Store, Action, Dispatch } from 'redux'
import { useState, useEffect } from 'react'

export function createUseRedux <S, A extends Action> (store: Store<S, A>) {
  function useRedux (): [S, Dispatch<A>]
  function useRedux <T> (selector: (state: S) => T): [T, Dispatch<A>]
  function useRedux (selector?: Function) {
    const [state, setState] = useState(() => store.getState())
    useEffect(() => store.subscribe(() => setState(store.getState())), [])

    return [selector ? selector(state) : state, store.dispatch]
  }

  return useRedux
}
```

Usage:
```typescript
// hooks.ts
import { createUseRedux } from 'react-use-redux'
import { store } from './store'
export const useRedux = createUseRedux(store)

// MyComponent.ts
import { useRedux } from './hooks'
const [value, dispatch] = useRedux(state => state.value)
```

**Comment by martynaskadisa** [comment]
Hey @sz-piotr 

Sorry for late response, I'm not actively maintaining this repo. I've only created it to explore possible API with hooks.

The official `react-redux` repo already has an _almost_ ready implementation with hooks (https://github.com/reduxjs/react-redux/releases/tag/v7.1.0-rc.1) so I would be betting on them since it is very popular, actively maintained and has a huge community.

**Comment by martynaskadisa** [comment]
I'm closing this as there is no point in using this library since `react-redux` supports hooks out the box.
